on:
  #Manual push
  workflow_dispatch:
  #Automated 
  push:
    paths:
      - 'input/**'

name: CreatePDFs

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mkrakowitzer/actions-makepdfs@v1.3
      if: github.ref == 'refs/heads/master'
      with:
        markdown_dir: input
        output_dir: output
    - uses: actions/upload-artifact@v4
      with:
        name: NASF PDFs
        path: output
