name: Release Markdown to PDF
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /input directory
    paths:
      - 'input/**.md'


jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: input
          output_dir: pdfs
          build_html: false
          

      - uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "dist/bin/ dist/shell/compiled.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
